### ISSUE TITLE
[Bug] Evento [The Frost Lord Ahune] entrega Emblemas de Escarcha

### ISSUE THREAD

**Issue by heavynetol** [Azerothserver/bugtracker#16]
El evento The Frost Lord Ahune entrega Emblemas de Escarcha. debido al parche en el que estamos, esos emblemas no deberían ser otorgados a los jugadores.

![WoWScrnShot_062119_115256](https://user-images.githubusercontent.com/52081894/59939069-481d1d80-9446-11e9-85e4-c3de7490ec1c.jpg)

**Comment by Norganx** [comment]
Solucionado.
Gracias por el reporte @heavynetol !!!
