### ISSUE TITLE
Bug, La mision ¡Buscar a Neltharaku! 

### ISSUE THREAD

**Issue by Arkilyus** [Azerothserver/bugtracker#17]
Sucede que al buscar al dragon Neltharaku, no se encuentra por la zona indicada ni aledaños.
Al parecer el NPC no se encuentra por la zona.
quest= https://es.wowhead.com/quest=10811/buscar-a-neltharaku

**Comment by Norganx** [comment]
Yo lo encontré y se mueve mucho.

![WoWScrnShot_062319_111310](https://user-images.githubusercontent.com/51986270/59979054-30f64100-95a8-11e9-8b5f-3ff1c20dde99.jpg)
![WoWScrnShot_062319_111333](https://user-images.githubusercontent.com/51986270/59979055-36538b80-95a8-11e9-8cc8-03b4b03306b1.jpg)
