### ISSUE TITLE
QUEST BUG : Decreto de La Cámara de las Sombras (CORONA DE HIELO-RASGANORTE)

### ISSUE THREAD

**Issue by manuel132122** [Azerothserver/bugtracker#18]
Quest: https://es.wowhead.com/quest=12943/decreto-de-la-c%C3%A1mara-de-las-sombras

No funciona el objeto ( Decreto de la cámara de las sombras) que te da la quest al momento de aceptarla y así poder activar el npc
Gracias.
![WoWScrnShot_062419_203103](https://user-images.githubusercontent.com/52184832/60062983-e61c1c80-96c0-11e9-8250-7d605f895668.jpg)
![WoWScrnShot_062419_203119](https://user-images.githubusercontent.com/52184832/60062985-e6b4b300-96c0-11e9-9c32-b30426e3b6a2.jpg)

**Comment by Norganx** [comment]
Debes estar ubicado en frente, no muy cerca ni muy lejos.

![WoWScrnShot_062519_030446](https://user-images.githubusercontent.com/51986270/60080959-7d4f9700-96f6-11e9-9bbf-801334975e4c.jpg)
![WoWScrnShot_062519_030510](https://user-images.githubusercontent.com/51986270/60080967-804a8780-96f6-11e9-9e50-ff0a8b4e5cf5.jpg)

**Comment by rod1cl** [comment]
La quest "Hoy Can't Miss Him" está bug,el npc Njormeld no está donde debería estar,y no puedo continuar la cadena con los hijos de hodir. Atte.

               Fury
