### ISSUE TITLE
Bug Huevo de Esencia mortal

### ISSUE THREAD

**Issue by Yayayadiel** [Azerothserver/bugtracker#37]
Buenas, he estado testeando un trinket por ya un buen rato que es el Huevo de Esencia mortal
https://es.wowhead.com/item=40685/el-huevo-de-esencia-mortal
Un trinket que se puede comprar con 40 chapas el cual su función es darte 505 de celeridad por Healing o Heal overtime.
Bien se sabe que es un abalorio para healer, pero también es usable para brujos usando Life tap o Transfución de vida.
Como se puede ver en este video del Retail: https://www.youtube.com/watch?v=LSmDEKxPeO8
Mas infos del funcionamiento del trinket en este foro: https://www.mmo-champion.com/threads/658602-The-Egg-of-Mortal-Essence

**Comment by Azerothserver** [comment]
NO tienes referencias relevantes. En el foro que colocas solo especulan de su uso y el video es del 2009 y tiene 183 visitas (con la mía).
Ya de por si me parecería incorrecto pero si puedes conseguir cambios en el changelog del oficial estaría mejor explicado o si fue fixeado en algún parche.

Gracias por el reporte igualmente.
