### ISSUE TITLE
Idolos del druida feral bug

### ISSUE THREAD

**Issue by parra93** [Azerothserver/bugtracker#38]
El ídiolo de adoración e ídolo de la bestia voraz no funcionan son nulos es como no llevarlos equipados, imágenes donde pruebo dps con ellos y luego sin usar ninguno, el daño es exactamente el mismo sin llevar nada puesto.

https://imgur.com/a/YVxsEgm

**Comment by Azerothserver** [comment]
una imagen del DPS no es una prueba contundente, mira tus stasts y si te suman.

Gracias por el reporte

**Comment by parra93** [comment]
las imágenes que mande no es para ver el total de dps, si los minimos y máximos con ídolo o sin el son el mismo es por que no esta funcionando
