### ISSUE TITLE
Curacion en Guardines Inmortales - Yogg-Saron

### ISSUE THREAD

**Issue by parra93** [Azerothserver/bugtracker#40]
En la modalidad 10  la curación que reciben los guardines inmortales es correcta haciendo la pelea posible y no tan complicada, por el contrario en la raid de 25 los adds están curándose incorrectamente el [debuff ](https://es.wowhead.com/spell=64486/sombras-potenciadas)solo debería curarles 750k por 20seg,con la reducción de sanación seria la mitad, pero están curándose mucho mas que eso, volviendo casi imposible la pelea

**Comment by Azerothserver** [comment]
Debes tener mas referencias como links a lo que te refieres, puedo suponer que es la que habilidad que se castea en un guardián para que cure a los demás?
Si es esa depende de ti si deseas dejarlo junto a otros guardianes o no.
