### ISSUE TITLE
Se bugeo la mision ,no aparece Espiritu sombraluna ancestral

### ISSUE THREAD

**Issue by Aborashdk** [Azerothserver/bugtracker#42]
Sr Gm buenas , el dia de ayer  la boticaria en la aldea sombra luna ,  me envio a buscar a Espiritu Sombraluna Ancestral , y lo encontre , me iva a dar 3 misiones dos de ellas elites , asi q decidi , seguir  mañana sin tomar ni una mision .... y al despertar aparecio otro npc llamado Teron sanguino .... por favor  SR GM  , ayudeme , necesito esas misiones , ya que me dan un casco de placas , el cual mas adelante transfigurare para un set q ya tengo en mente .... es necesario , tmb el pj de mi hermano le envio a buscar a ese npc y no aparece , parece ser q alguien mas tomo la mision y no la completo ,por favor ayudenos gracias , cada rato voy a ver si se restablecio pero nada ... gracias SR GM ... por favor ayudeme .
![WoWScrnShot_082319_002333](https://user-images.githubusercontent.com/54429691/63568811-52d65a80-c53c-11e9-8c8d-bd373d4686ed.jpg)

**Comment by Azerothserver** [comment]
Si es una misión con un minievento prueba olvidarle y tomarla nuevamente. Esto debe estar en soporte técnico y asesorarte con otros jugadores o un moderador. No en reporte de bug.

**Comment by Aborashdk** [comment]
lo hize , mi hermano y unos amigos tomaron la mision desde el inicio y no les aparecio el npn ,  en mi caso si me aparecio el dia de ayer , pero no tome la mision q seguia por q era de matar elite y decidi hacerla al dia siguiente por q ya era tarde , Da un casco q necesito  para transfigurar ... :C  ese npc q aparece es la forma q debe de tomar  el " espiritu sombraluna ancestral " al hacer las misiones que da , ese te da otra mision y luego el item... a mi hermano y amigos ,  la boticaria les envia a encontrarlo pero no aparece ,  a mi me envio y lo encontre , entrege mision y luego me dio la opcion de pedir otras pero no pedi, decidi dejarla para el dia siguiente y al logear , aparecio ese npc q es la forma final de la mision , es como si alguien hubiera hecho las misiones q da y ya no termino ... solo se fue ... ya no se puede pedir... si cae el server quizas aparesca ese npc... Gracias 
![espiritu](https://user-images.githubusercontent.com/54429691/63582897-85457f00-c55f-11e9-9d80-9eb8c6f413cb.png)

**Comment by Aborashdk** [comment]
SE SOLUCIONO !!! muchas gracias !! ahora seguire con mi cruzada :v
