### ISSUE TITLE
BUG Velocidad de Esferas Valquirias 25H

### ISSUE THREAD

**Issue by Whisper-Warr** [Azerothserver/bugtracker#45]
Podrian revisar el evento de valquirias 25H la velocidad y el daño de esas esferas es muy elevado, viendo en el video del servidor original se puede ver que no es la misma velocidad con la que las esferas se mueven alrededor de la sala, y tambien estas esferas  aqui en el server se lanzan directo a ti sin darte la posibilidad de esquivar 
Aqui les dejo un video del first kill de Valquirias 25H Por la Hermandad Ensidia (EU) https://www.method.gg/video/qo7iY3RYd94

**Comment by Azerothserver** [comment]
El evento esta con los últimos cambios agregados por blizzard y ya es muy sencillo cuando los jugadores dominan dicho evento.
