### ISSUE TITLE
Problmas con la faccion hijos de hodir

### ISSUE THREAD

**Issue by marcovsr** [Azerothserver/bugtracker#52]
**Npc Hijos de hodir**
Indica que es: no puedo compara las cosas de los npc delso hijos de hodir 
**Describe el Fallo**
Empece realizando la cadena de misiones para poder ser amigable conlos hijos de hodir cuando termine la cadena de misiones enseguida quede como exaltado, ahora que quiero ir a comparar las cosas conl os hijos de Hodir, no me aperece ningun Npc ene lcaul pueda comprar y me sigue slaidno los npcs moviedones y las valkys congeladas.

**Comment by Azerothserver** [comment]
Es un error general de los jugadores al no saber completar toda la cadena.
Busca soporte en discord muchos players y moderadores podrán orientarte.
