### ISSUE TITLE
Problema con Pj (Dudu)

### ISSUE THREAD

**Issue by Espectrok** [Azerothserver/bugtracker#53]
**Tipo/Ubicación del fallo**
Indica que es: Pj druida luzzbell, 
Ubicacion: Cualquier parte de rasganorte, kalimdor, reinos del este
Tiempo: Momentos aletorios

**Describe el Fallo**
Buenas veran tengo un problema, en la actualidad hay veces que el server me bota solo al druida , logeo otra cuenta cualquiera y va todo normal pero logeo al druida y lo sabe botar(desconectar),problemas de ent no creo que sea porque tranquilamente botaria  mis dos cuentas al mismo tiempo y no solo 1 e tenido abierta hasta 3 cuentas y va sin novedad, otro problema seria que no puedo ver a los personajes  e  hecho la prueba teniendo mis dos personajes juntos  y en la cuenta del dudu no me deja ver a otros personajes y cuando doy grupo tampoco me deja debo aveces desconectar pa ver si se arregla,
Yo e borrado cache,carpeta wtf, e borrado el juego y descargado uno nuevo, e desactivado addons, e jugado sin addons, e probado en dos compus distintas(por si acaso sea mi computadora), y el problema persiste, me dijeron que debo postear para ver que pasaba con mi cuenta, 

**Descarta problemas del tu cliente de juego**
 - Borra cache y verifica si tu problema persiste.   (Lo  hice y aun asi persiste el problema)
 - En caso sea necesario descarga una nueva copia del juego 3.3.5  (Borre todo el juego y descargue una nueva copia y aun asi persiste}
 - Desactiva addons y cierra cualquier otra aplicación en la PC.  (Igualmente pensé que era addons desactive-borre y aun seguia)

**Comment by Azerothserver** [comment]
El problema que presentas puede ser individual y si ya descartaste el cliente de juego tendrías que pasar un breve revisión de un GM de alto rango.
Envíame un mensaje a Norgan y veremos ingame que le pasa a tu personaje.
