### ISSUE TITLE
Bichos bug de posición y de ataque.

### ISSUE THREAD

**Issue by Maycolx** [Azerothserver/bugtracker#54]
**Tipo/Ubicación del fallo**
Npc

**Describe el Fallo**
En corona de hielo cuando vas a pegar un add se mueve de posición pero visualmente está en otro lado, lo que ocasiona que no puedas pegarle porque no está en el lugar que crees y que el no pueda pegarte pero debe ser por el mismo fallo. Una cosa más es que cuando los matas vuelven a la posición realmente en la que estaba.

**Como reproducir el fallo**
Paso para reproducir lo que reportas:

Simplemente pegandoles.

4. Ver el error

**Como debería funcionar**
Un combate normal.

**Screenshots and Videos**
https://www.youtube.com/watch?v=FlKLXFyrQc8&t=188s

**Descarta problemas del tu cliente de juego**
No es el problema.

**Comment by Azerothserver** [comment]
Es un error general de mapas ya fu corregido, gracias por el reporte.
