### ISSUE TITLE
Bug con la misión "Encuentra la filacteria"

### ISSUE THREAD

**Issue by Rayleiigh** [Azerothserver/bugtracker#58]
Buenas noches, mi personaje se llama Rayleiight, la misión "Encuentra la filacteria" se encuentra bug ya que para poder completarla hay que sumergirse en un lago de Tundra para poder activar un cristal debajo del  lago y completarla pero el lago se encuentra "congelado" o no se como describirlo de otra manera ya que no se puede sumergir en el, literalmente te obliga a caminar sobre el lago, lo cual no deberia pasar. Necesito hacer esta mision ya que es la primera misión de la cadena para poder conseguir la Acha de la muerte congelada. muchas gracias de ante mano a quien corrija el error.

**Comment by Azerothserver** [comment]
La misión funciona perfectamente sin fallos, hay un punto de agua donde marque el mismo juego para completarla.
