### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by vikthor123** [Azerothserver/bugtracker#59]
**Tipo/Ubicación del fallo**
Indica que es: item, misión, habilidad, Npc, Etc.

**Describe el Fallo**
La mision de la purificacion de Quel'delar esta bug no completa la mision.
la espada desaparece sin dejar objeto de mision

**Como reproducir el fallo**
Paso para reproducir lo que reportas:
1. Ir a '...'
2. Click en '....'
3. Hacer que '....'
4. Ver el error

**Como debería funcionar**
Una descripción clara y concisa de lo que esperaba que sucediera. Debes usar referencias al Wow oficial 3.3.5 WotLK. (Si refieres otros servidores privados puede no ser tomado en cuenta)

**Screenshots and Videos**
Para un mejor reporte, agregué capturas de pantalla o videos para ayudar a explicar su problema.

**Descarta problemas del tu cliente de juego**
 - Borra cache y verifica si tu problema persiste.
 - En caso sea necesario descarga una nueva copia del juego 3.3.5
 - Desactiva addons y cierra cualquier otra aplicación en la PC.

**RECOMENDACIONES:**
 - Usa nuestra DataBase: www.azerothwotlk.com
 - Sube imágenes/videos con buena resolución.
 - Consulta los canales de soporte para confirmar tu reporte.

**Contexto Adicional**
Agregue cualquier otro contexto sobre el problema aquí.

**Comment by Azerothserver** [comment]
Un error común de los jugadores es que hacen la misión estando en banda, en banda no puedes hacer quest personales o de grupo.
